echo off

REM CLASS 0 % range of number of cores
set CLASS0_MIN_CORES=50
set CLASS0_MAX_CORE=50

REM CLASS 1 % range of number of cores
set CLASS1_MIN_CORES=50
set CLASS1_MAX_CORE=50

REM CLASS 0 % range of processor frequency
set CLASS0_MIN_FREQ=8
set CLASS0_MAX_FREQ=100

REM CLASS 1 % range of processor frequency
set CLASS1_MIN_FREQ=8
set CLASS1_MAX_FREQ=100

REM CLASS 0 % range of number of cores
powercfg /SETACVALUEINDEX OVERLAY_SCHEME_MAX SUB_PROCESSOR CPMINCORES %CLASS0_MIN_CORES%
powercfg /SETDCVALUEINDEX OVERLAY_SCHEME_MAX SUB_PROCESSOR CPMINCORES %CLASS0_MIN_CORES%
powercfg /SETACVALUEINDEX OVERLAY_SCHEME_MAX SUB_PROCESSOR CPMAXCORES %CLASS0_MAX_CORE%
powercfg /SETDCVALUEINDEX OVERLAY_SCHEME_MAX SUB_PROCESSOR CPMAXCORES %CLASS0_MAX_CORE%

REM CLASS 1 % range of number of cores
powercfg /SETACVALUEINDEX OVERLAY_SCHEME_MAX SUB_PROCESSOR CPMINCORES1 %CLASS1_MIN_CORES%
powercfg /SETDCVALUEINDEX OVERLAY_SCHEME_MAX SUB_PROCESSOR CPMINCORES1 %CLASS1_MIN_CORES%
powercfg /SETACVALUEINDEX OVERLAY_SCHEME_MAX SUB_PROCESSOR CPMAXCORES1 %CLASS1_MAX_CORE%
powercfg /SETDCVALUEINDEX OVERLAY_SCHEME_MAX SUB_PROCESSOR CPMAXCORES1 %CLASS1_MAX_CORE%

REM CLASS 0 % range of processor frequency
powercfg /SETACVALUEINDEX OVERLAY_SCHEME_MAX SUB_PROCESSOR PROCTHROTTLEMIN %CLASS0_MIN_FREQ%
powercfg /SETDCVALUEINDEX OVERLAY_SCHEME_MAX SUB_PROCESSOR PROCTHROTTLEMIN %CLASS0_MIN_FREQ%
powercfg /SETACVALUEINDEX OVERLAY_SCHEME_MAX SUB_PROCESSOR PROCTHROTTLEMAX %CLASS0_MAX_FREQ%
powercfg /SETDCVALUEINDEX OVERLAY_SCHEME_MAX SUB_PROCESSOR PROCTHROTTLEMAX %CLASS0_MAX_FREQ%

REM CLASS 1 % range of processor frequency
powercfg /SETACVALUEINDEX OVERLAY_SCHEME_MAX SUB_PROCESSOR PROCTHROTTLEMIN1 %CLASS1_MIN_FREQ%
powercfg /SETDCVALUEINDEX OVERLAY_SCHEME_MAX SUB_PROCESSOR PROCTHROTTLEMIN1 %CLASS1_MIN_FREQ%
powercfg /SETACVALUEINDEX OVERLAY_SCHEME_MAX SUB_PROCESSOR PROCTHROTTLEMAX1 %CLASS1_MAX_FREQ%
powercfg /SETDCVALUEINDEX OVERLAY_SCHEME_MAX SUB_PROCESSOR PROCTHROTTLEMAX1 %CLASS1_MAX_FREQ%

powercfg /overlaysetactive OVERLAY_SCHEME_MAX

